-- Sales Performance Analysis


-- 1.1 Which are the top 10 best-selling books based on the total quantity sold?

SELECT 
	b.Book_ID,
    b.Title,
    SUM(o.Quantity) AS total_quantity
FROM Books b
JOIN Orders o 
	ON b.Book_ID = o.Book_ID
GROUP BY 
	b.Book_ID,
    b.Title
ORDER BY total_quantity DESC 
LIMIT 10;


-- 1.2 Which book genres generated the highest total revenue?

SELECT 
	Genre,
    SUM(Total_Amount) AS total_revenue
FROM Orders o 
JOIN Books b 
	ON b.Book_ID = o.Book_ID
GROUP BY 
	Genre
ORDER BY total_revenue DESC
LIMIT 1;


    
-- 1.3 What is the total revenue generated by each author?


SELECT 
	b.Author,
    SUM(o.Total_Amount) AS revenue_generated
FROM Orders o
JOIN Books b
	ON b.Book_ID = o.Book_ID
GROUP BY 
	b.Author;



-- 1.4 Which books have generated the highest revenue?

SELECT 
	b.Title,
    SUM(o.Total_Amount) as Higest_revenue
FROM Orders o
JOIN Books b
	ON b.Book_ID = o.Book_ID
GROUP BY 
	b.Title
ORDER BY Higest_revenue DESC;



-- 1.5 Which books generated high revenue despite having relatively low sales volume?


WITH book_sales_summary AS (
SELECT 
	b.Title,
    SUM(o.Quantity) AS copies_sold,
	SUM(o.Total_Amount) AS revenue_generated
FROM Orders o
JOIN Books b
	ON b.Book_ID = o.Book_ID
GROUP BY 
	b.Title
)

SELECT 
	Title, 
    copies_sold,
    revenue_generated
FROM book_sales_summary
WHERE 
	copies_sold < (SELECT AVG(copies_sold) FROM book_sales_summary)
    AND 
    revenue_generated > (SELECT AVG(revenue_generated) FROM book_sales_summary);
    
    



















    